"""empty message

Revision ID: da6d0e1e6519
Revises: f0e3ec45c085
Create Date: 2025-02-24 14:38:19.094595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da6d0e1e6519'
down_revision = 'f0e3ec45c085'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_column('homeworld_id')
        batch_op.drop_column('starships_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('starships_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('homeworld_id', sa.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
