"""empty message

Revision ID: f4e518d7b655
Revises: 1c4f32ee7766
Create Date: 2025-02-11 01:07:28.232288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4e518d7b655'
down_revision = '1c4f32ee7766'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=15), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('item', sa.String(length=30), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planets',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('diameter', sa.String(length=15), nullable=False),
    sa.Column('rotation_period', sa.String(length=15), nullable=False),
    sa.Column('orbital_period', sa.String(length=15), nullable=False),
    sa.Column('population', sa.String(length=20), nullable=False),
    sa.Column('climate', sa.String(length=15), nullable=False),
    sa.Column('terrain', sa.String(length=15), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['favorites.id'], ),
    sa.ForeignKeyConstraint(['uid'], ['favorites.id'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('starships',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('model', sa.String(length=30), nullable=False),
    sa.Column('starship_class', sa.String(length=30), nullable=False),
    sa.Column('cost_in_credits', sa.String(length=30), nullable=False),
    sa.Column('crew', sa.String(length=30), nullable=False),
    sa.Column('hyperdrive_rating', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['favorites.id'], ),
    sa.ForeignKeyConstraint(['uid'], ['favorites.id'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('characters',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('birth_year', sa.String(length=30), nullable=False),
    sa.Column('gender', sa.String(length=30), nullable=False),
    sa.Column('homeworld_id', sa.Integer(), nullable=False),
    sa.Column('starships_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['favorites.id'], ),
    sa.ForeignKeyConstraint(['homeworld_id'], ['planets.uid'], ),
    sa.ForeignKeyConstraint(['starships_id'], ['starships.uid'], ),
    sa.ForeignKeyConstraint(['uid'], ['favorites.id'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('firstname', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('lastname', sa.String(length=20), nullable=False))
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=30),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['username'])
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('email',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
        batch_op.drop_column('lastname')
        batch_op.drop_column('firstname')
        batch_op.drop_column('username')

    op.drop_table('characters')
    op.drop_table('starships')
    op.drop_table('planets')
    op.drop_table('favorites')
    # ### end Alembic commands ###
